spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sample-specification}
    username: ${DB_USER:sample}
    password: ${DB_PASSWORD:sample}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    schemas: public
